logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.transaction: DEBUG

spring.jpa.hibernate.ddl-auto: update

DATASOURCE_URL: jdbc:postgresql://localhost:5432/app
DATASOURCE_USERNAME: postgres
DATASOURCE_PASSWORD: admin123
